# Group Promo

In [5]:
#Import Library

import pandas as pd
from itertools import product

In [6]:
#Definisi Karakter

aktif=['Aktif', 'Tidak Aktif']
ps = ['Tinggi', 'Rendah']
gender = ['Pria', 'Wanita']
category = ['Gold', 'Silver']

In [7]:
#Data Frame Combinations
"""
Data Frame Combinations dibuat menggunakan method product() dari itertools untuk mendapatkan kombinasi sebanyak 2^n.
"""

dfc=pd.DataFrame(list(product(aktif,ps, gender,category)), columns=['Keaktifan','Purchasing Store', 'Gender','Category'])
dfc.insert(0, 'Group Promo', range(1, 1 + len(dfc)))
dfc

    Group Promo    Keaktifan Purchasing Store  Gender Category
0             1        Aktif           Tinggi    Pria     Gold
1             2        Aktif           Tinggi    Pria   Silver
2             3        Aktif           Tinggi  Wanita     Gold
3             4        Aktif           Tinggi  Wanita   Silver
4             5        Aktif           Rendah    Pria     Gold
5             6        Aktif           Rendah    Pria   Silver
6             7        Aktif           Rendah  Wanita     Gold
7             8        Aktif           Rendah  Wanita   Silver
8             9  Tidak Aktif           Tinggi    Pria     Gold
9            10  Tidak Aktif           Tinggi    Pria   Silver
10           11  Tidak Aktif           Tinggi  Wanita     Gold
11           12  Tidak Aktif           Tinggi  Wanita   Silver
12           13  Tidak Aktif           Rendah    Pria     Gold
13           14  Tidak Aktif           Rendah    Pria   Silver
14           15  Tidak Aktif           Rendah  Wanita     Gold
15           16  Tidak Aktif           Rendah  Wanita   Silver

In [8]:
#Input Customer Name dan Customer Data

customer_name=input("Masukkan nama: ")

#customer_data = ['Tidak Aktif', 'Rendah', 'Pria', 'Gold']  

customer_data_act=input("Masukkan status keaktifan (Aktif/Tidak Aktif): ")
customer_data_ps=input("Masukkan purchasing store (Tinggi/Rendah): ")
customer_data_gender=input("Masukkan gender (Pria/Wanita): ")
customer_data_cat=input("Masukkan kategori (Gold/Silver): ")

Masukkan nama: Cahya
Masukkan status keaktifan (Aktif/Tidak Aktif): Tidak Aktif
Masukkan purchasing store (Tinggi/Rendah): Rendah
Masukkan gender (Pria/Wanita): Pria
Masukkan kategori (Gold/Silver): Gold

In [9]:
#Menentukan Group Promo

customer_input = dfc[(dfc['Keaktifan']  == customer_data_act) & (dfc['Purchasing Store'] == customer_data_ps)
         & (dfc['Gender']  == customer_data_gender) & (dfc['Category']  == customer_data_cat)]
index=customer_input.index.item()

In [10]:
#Output

print(customer_name, "masuk ke dalam group promo:", index+1)

Cahya masuk ke dalam group promo: 13

# Potensi Group

In [17]:
#Definisi Fungsi Potensi Group Customer
"""
Alur fungsi:

1. Dua parameter yang digunakan yaitu customer_name dengan tipe string dan customer_data dengan tipe data list

2. Program akan memeriksa apakah ada data hilang yang ditandai dengan "-" pada list customer_data.

3. Jika ada data hilang, maka:  
   a. Program akan mengambil info index data hilang tersebut dan disimpan di sebuah variabel 'result'
   b. Jika data hilang ada pada index ke-0, maka baris pada dataframe yang memiliki data purchasing store, gender, dan category
      yang sama dengan customer_data akan diambil dan disimpan pada variabel 'customer_input'. Lalu, diambil list dari baris 
      tersebut terletak pada index ke-berapa saja dan disimpan pada variabel 'customer_group'.
   c. Jika data hilang ada pada index ke-1, maka baris pada dataframe yang memiliki data keaktifan, gender, dan category
      yang sama dengan customer_data akan diambil dan disimpan pada variabel 'customer_input'. Lalu, diambil list dari baris 
      tersebut terletak pada index ke-berapa saja dan disimpan pada variabel 'customer_group'.
   d. Jika data hilang ada pada index ke-2, maka baris pada dataframe yang memiliki data keaktifan,purchasing store, dan category
      yang sama dengan customer_data akan diambil dan disimpan pada variabel 'customer_input'. Lalu, diambil list dari baris 
      tersebut terletak pada index ke-berapa saja dan disimpan pada variabel 'customer_group'.
   e. Jika data hilang ada pada index ke-3, maka baris pada dataframe yang memiliki data keaktifan, purchasing store, dan gender
      yang sama dengan customer_data akan diambil dan disimpan pada variabel 'customer_input'. Lalu, diambil list dari baris 
      tersebut terletak pada index ke-berapa saja dan disimpan pada variabel 'customer_group'.
   f. Setiap indeks dalam list customer_group akan ditambah dengan 1 untuk menunjukkan potensi group promonya.

4. Jika tidak ada data hilang, maka:
   a. Baris pada dataframe yang memiliki data keaktifan, purchasing store, gender, dan category yang sama dengan customer_data 
      akan diambil dan disimpan pada variabel 'customer_input'.
   b. Diambil index dari baris tersebut bertipe integer dan ditambah dengan 1 untuk menunjukkan group promonya, 
      lalu disimpan pada variabel 'customer_group'.
   c. Variabel customer_group dijadikan list.
   
5. Fungsi mengembalikan variabel list customer_group

"""

def potential_customer_group(customer_name, customer_data):
    if '-' in customer_data:
        result = customer_data.index('-')
        if result==0:
            customer_input = dfc[(dfc['Purchasing Store'] == customer_data[1])
            & (dfc['Gender']  == customer_data[2]) & (dfc['Category']  == customer_data[3])]
            customer_group=(customer_input.index.tolist())
        elif result==1:
            customer_input = dfc[(dfc['Keaktifan'] == customer_data[0])
            & (dfc['Gender']  == customer_data[2]) & (dfc['Category']  == customer_data[3])]
            customer_group=(customer_input.index.tolist())
        elif result==2:
            customer_input = dfc[(dfc['Keaktifan'] == customer_data[0])
            & (dfc['Purchasing Store']  == customer_data[1]) & (dfc['Category']  == customer_data[3])]
            customer_group=(customer_input.index.tolist())
        elif result==3:
            customer_input = dfc[(dfc['Keaktifan'] == customer_data[0])
            & (dfc['Purchasing Store']  == customer_data[1]) & (dfc['Gender']  == customer_data[2])]
            customer_group=(customer_input.index.tolist())
        
        for i in range(len(customer_group)):
            customer_group[i] +=1
    
    else:
        customer_input = dfc[(dfc['Keaktifan']  == customer_data[0]) & (dfc['Purchasing Store'] == customer_data[1])
         & (dfc['Gender']  == customer_data[2]) & (dfc['Category']  == customer_data[3])]
        group=customer_input.index.item()+1
        customer_group= [group]
    
    return customer_group

In [18]:
# input 1
customer_name_1 = 'cahya'
customer_data_1 = ['Tidak Aktif', '-', 'Pria', 'Gold']
 
# input 2
customer_name_2 = 'faizal'
customer_data_2 = ['-', 'Rendah', 'Pria', 'Gold']
 
# input 3
customer_name_3 = 'ana'
customer_data_3 = ['Aktif', 'Rendah', 'Wanita', 'Gold']

In [19]:
#Output
"""
Maaf, dalam assigment yang diberikan, saya kira ada kekeliruan dalam output customer 2, mohon maaf jika saya salah
"""

print(customer_name_1,"berpotensi masuk ke dalam group promo:",potential_customer_group(customer_name_1, customer_data_1))
print(customer_name_2,"berpotensi masuk ke dalam group promo:",potential_customer_group(customer_name_2, customer_data_2))
print(customer_name_3,"masuk ke dalam grup promo:",potential_customer_group(customer_name_3, customer_data_3))

cahya berpotensi masuk ke dalam group promo: [9, 13]
faizal berpotensi masuk ke dalam group promo: [5, 13]
ana masuk ke dalam grup promo: [7]